# Generated by Django 4.1.3 on 2023-01-31 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_catalogo', models.CharField(max_length=80)),
                ('valor', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=10)),
                ('actividad', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=80)),
                ('apellidos', models.CharField(max_length=80)),
                ('cedula', models.CharField(max_length=10)),
                ('fecha_nacimiento', models.DateField()),
                ('direccion', models.CharField(max_length=100)),
                ('convencional', models.CharField(max_length=7)),
                ('celular', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=50)),
                ('aceptado', models.BooleanField(blank=True)),
                ('rsov_propietario', models.CharField(max_length=50)),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.institucion')),
                ('sexo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.catalogo')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fk_catalogo', to='api.catalogo')),
            ],
        ),
    ]
