# Generated by Django 4.1.3 on 2023-02-05 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_persona_rsov_propietario'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='etnia',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.PROTECT, related_name='fk_catalogoEtnia', to='api.catalogo'),
            preserve_default=False,
        ),
    ]
